# Generated by Django 5.2 on 2025-04-26 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('area', models.CharField(choices=[('MAT', 'Matemática'), ('NAT', 'Ciências da Natureza'), ('LING', 'Linguagens e Códigos'), ('HUM', 'Ciências Humanas')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizacao', models.DateTimeField(auto_now_add=True)),
                ('nota_matematica', models.FloatField()),
                ('nota_natureza', models.FloatField()),
                ('nota_linguagens', models.FloatField()),
                ('nota_humanas', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoDeEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridade', models.IntegerField(choices=[(1, 'Alta'), (2, 'Média'), (3, 'Baixa')])),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20)),
                ('recomendacao', models.TextField(blank=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostico.competencia')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='diagnostico.diagnostico')),
            ],
        ),
    ]
